catalog:
  '@antv/layout': 1.2.14-beta.8
  '@antv/x6': ^3.1.6
  '@nuxt/ui': ^4.5.1
  '@vueuse/core': ^14.2.1
  eslint: ^10.0.3
  nuxt: ^4.4.2
  tailwindcss: ^4.2.1
  typescript: ^5.9.3

catalogMode: prefer

catalogs:
  edit:
    '@antv/x6-vue-shape': ^3.0.2
  infra:
    '@promise2/eslint-config': ^0.4.0
    nano-staged: ^0.9.0
    simple-git-hooks: ^2.13.1
  nuxt:
    '@nuxt/eslint': ^1.15.2
    '@vueuse/nuxt': ^14.2.1
    vue-tsc: ^3.2.5
  ui:
    '@iconify-json/lucide': ^1.2.98
    '@iconify-json/simple-icons': ^1.2.74

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
overrides:
  serialize-javascript@<=7.0.2: '>=7.0.3'
